import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from './providers';
import { CheckCircle, XCircle, Info, AlertTriangle } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
        <Toaster
          icons={{
            success: <CheckCircle className="text-green-500 w-4 h-4 mt-1" />,
            error: <XCircle className="text-red-500 w-4 h-4 mt-1" />,
            info: <Info className="text-blue-500 w-4 h-4 mt-1" />,
            warning: <AlertTriangle className="text-yellow-500 w-4 h-4 mt-1" />,
          }}

        />

      </body>
    </html>
  );
}

